### ISSUE TITLE
Error while running the make file

### ISSUE THREAD

**Issue by ghost** [hellosunking/Msuite2#8]
I did run the Example 1 command, the make file created. But I get error while I trying to run the 'make' file. 

(make) [lp176@compute-e-16-233 output_pub]$ make
/n/scratch3/users/l/lp176/Msuite2-master/bin/preprocessor.pe /n/scratch3/users/l/lp176/GSE205056/SRR19441362_1.fastq.gz /n/scratch3/users/l/lp176/GSE205056/SRR19441362_2.fastq.gz 150 Msuite2 3 8 36 53 illumina 0 0 0 0
make: /n/scratch3/users/l/lp176/Msuite2-master/bin/preprocessor.pe: Command not found
make: *** [makefile:6: Msuite2.trim.log] Error 127

Thank you to resolve the issue!

**Comment by hellosunking** [comment]
Hi,

You can see that the error information is the "command not found". Did you move Msuite2 package to another directory after building the makefile? Or did you run "make clean" without a following "make"? Please check.

Kun

**Comment by ghost** [comment]
Thank you the problem were solved. Thank you!
